# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MoekEditorDockWidget
                                 A QGIS plugin
 Wtyczka do obsługi systemu MOEK (PIG-PIB).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-12
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Dominik Szrek / PIG-PIB
        email                : dszr@pgi.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import Qt, QSize
from PyQt5.QtWidgets import QShortcut
from qgis.PyQt.QtCore import pyqtSignal
from PyQt5.QtGui import QIcon, QPixmap
from qgis.core import QgsProject
from qgis.utils import iface

from .viewnet import change_done, vn_change, vn_powsel, vn_polysel, vn_add, vn_sub, vn_zoom
from .viewnet import hk_up_pressed, hk_down_pressed, hk_left_pressed, hk_right_pressed
from .classes import IdentMapTool, PolySelMapTool
from .widgets import MoekPanel

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'moek_editor_dockwidget_base.ui'))
ICON_PATH = os.path.dirname(os.path.realpath(__file__)) + os.path.sep + 'ui' + os.path.sep
SELF = "self."

class MoekEditorDockWidget(QtWidgets.QDockWidget, FORM_CLASS):  #type: ignore

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(MoekEditorDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.iface = iface
        self.setupUi(self)

        p_vn_widgets = [
                    {"page": 0, "row": 0, "col": 0, "r_span": 1, "c_span": 1, "item": "button", "name": "vn_sel", "size": 50, "checkable": True, "tooltip": u"wybierz pole"},
                    {"page": 0, "row": 0, "col": 1, "r_span": 1, "c_span": 1, "item": "button", "name": "vn_zoom", "size": 50, "checkable": False, "tooltip": u"przybliż do pola"},
                    {"page": 0, "row": 0, "col": 2, "r_span": 1, "c_span": 1, "item": "button", "name": "vn_done", "size": 50, "checkable": False, "tooltip": u'oznacz jako "SPRAWDZONE"'},
                    {"page": 0, "row": 0, "col": 3, "r_span": 1, "c_span": 1, "item": "button", "name": "vn_doneF", "size": 50, "checkable": False, "tooltip": u'oznacz jako "SPRAWDZONE" i idź do następnego'},
                    {"page": 1, "row": 0, "col": 0, "r_span": 1, "c_span": 3, "item": "combobox", "name": "team_users"},
                    {"page": 1, "row": 1, "col": 0, "r_span": 1, "c_span": 1, "item": "button", "name": "vn_powsel", "size": 50, "checkable": True, "tooltip": u"zaznacz pola siatki widoków znajdujące się w granicach wybranego powiatu"},
                    {"page": 1, "row": 1, "col": 1, "r_span": 1, "c_span": 1, "item": "button", "name": "vn_polysel", "size": 50, "checkable": True, "tooltip": u"zaznacz pola znajdujące się w granicach narysowanego poligonu"},
                    {"page": 1, "row": 1, "col": 2, "r_span": 1, "c_span": 1, "item": "button", "name": "vn_unsel", "size": 50, "checkable": False, "tooltip": u"wyczyść zaznaczenie pól siatki widoków"},
                    {"page": 1, "row": 0, "col": 3, "r_span": 1, "c_span": 1, "item": "button", "name": "vn_add", "size": 50, "checkable": False, "tooltip": u"dodaj wybrane pola siatki widoków do zakresu poszukiwań wskazanego użytkownika"},
                    {"page": 1, "row": 1, "col": 3, "r_span": 1, "c_span": 1, "item": "button", "name": "vn_sub", "size": 50, "checkable": False, "tooltip": u"odejmij wybrane pola siatki widoków od zakresu poszukiwań wskazanego użytkownika"}
                    ]

        self.p_vn = MoekPanel(title="Siatka widoków",
                            io_fn="vn_load()",
                            config=True,
                            cfg_fn="vn_setup_mode(self.cfg_btn.isChecked())",
                            pages=2)
        self.vl_main.addWidget(self.p_vn)
        self.frm_main.setLayout(self.vl_main)
        for widget in p_vn_widgets:
            if widget["item"] == "button":
                self.p_vn.add_button(widget)
            elif widget["item"] == "combobox":
                self.p_vn.add_combobox(widget)

        self.__button_conn()

        hotkeys = {"hk_up": "Up", "hk_down": "Down", "hk_left": "Left", "hk_right": "Right", "hk_space": "Space"}

        for key, val in hotkeys.items():
            exec(SELF + key + " = QShortcut(Qt.Key_" + val + ", iface.mainWindow())")

    def toggle_hk(self, enabled):
        hotkeys = {"hk_up": "hk_up_pressed",
                   "hk_down": "hk_down_pressed",
                   "hk_left": "hk_left_pressed",
                   "hk_right": "hk_right_pressed",
                   "hk_space": "lambda: change_done(True)"}
        io = "connect" if enabled else "disconnect"
        try:
            for key, val in hotkeys.items():
                exec(SELF + key + ".setEnabled(enabled)")
                exec(SELF + key + ".activated." + io + "(" + val + ")")
        except Exception as error:
            print("hotkeys exception: {}".format(error))

    def __button_conn(self):
        """Przyłączenia przycisków do funkcji."""
        self.p_vn.widgets["btn_vn_sel"].clicked.connect(lambda: self.ident_mt_init(self.p_vn.widgets["btn_vn_sel"], "vn_user", vn_change))
        self.p_vn.widgets["btn_vn_zoom"].pressed.connect(vn_zoom)
        self.p_vn.widgets["btn_vn_done"].pressed.connect(lambda: change_done(False))
        self.p_vn.widgets["btn_vn_doneF"].pressed.connect(lambda: change_done(True))
        self.p_vn.widgets["btn_vn_powsel"].clicked.connect(lambda: self.ident_mt_init(self.p_vn.widgets["btn_vn_powsel"], "mv_team_powiaty", vn_powsel))
        self.p_vn.widgets["btn_vn_polysel"].clicked.connect(lambda: self.poly_mt_init(self.p_vn.widgets["btn_vn_polysel"], vn_polysel))
        self.p_vn.widgets["btn_vn_unsel"].pressed.connect(lambda: QgsProject.instance().mapLayersByName("vn_all")[0].removeSelection())
        self.p_vn.widgets["btn_vn_add"].pressed.connect(vn_add)
        self.p_vn.widgets["btn_vn_sub"].pressed.connect(vn_sub)

    def button_cfg(self, btn, icon_name, size=50, tooltip=""):
        """Konfiguracja przycisków."""
        btn.setToolTip(tooltip)
        icon = QIcon()
        icon.addFile(ICON_PATH + icon_name + "_0.png", size=QSize(size, size), mode=QIcon.Normal, state=QIcon.Off)
        icon.addFile(ICON_PATH + icon_name + "_0_act.png", size=QSize(size, size), mode=QIcon.Active, state=QIcon.Off)
        icon.addFile(ICON_PATH + icon_name + "_0.png", size=QSize(size, size), mode=QIcon.Selected, state=QIcon.Off)
        if not btn.isEnabled():
            icon.addFile(ICON_PATH + icon_name + "_0_dis.png", size=QSize(size, size), mode=QIcon.Disabled, state=QIcon.Off)
        if btn.isCheckable():
            icon.addFile(ICON_PATH + icon_name + "_1.png", size=QSize(size, size), mode=QIcon.Normal, state=QIcon.On)
            icon.addFile(ICON_PATH + icon_name + "_1_act.png", size=QSize(size, size), mode=QIcon.Active, state=QIcon.On)
            icon.addFile(ICON_PATH + icon_name + "_1.png", size=QSize(size, size), mode=QIcon.Selected, state=QIcon.On)
        btn.setIcon(icon)

    def ident_mt_init(self, btn, layer_name, callback):
        """Initializacja maptool'a do identyfikacji obiektu na określonej warstwie."""
        canvas = self.iface.mapCanvas()
        layer = QgsProject.instance().mapLayersByName(layer_name)[0]
        if btn.isChecked() is False:
            canvas.unsetMapTool(self.maptool)
            return
        self.maptool = IdentMapTool(canvas, layer)
        self.maptool.identified.connect(callback)
        canvas.setMapTool(self.maptool)

    def poly_mt_init(self, btn, callback):
        """Initializacja maptool'a do poligonalnego zaznaczania obiektów na określonej warstwie."""
        canvas = self.iface.mapCanvas()
        if btn.isChecked() is False:
            canvas.unsetMapTool(self.maptool)
            return
        self.maptool = PolySelMapTool(canvas)
        self.maptool.selected.connect(callback)
        canvas.setMapTool(self.maptool)

    def closeEvent(self, event):
        self.toggle_hk(False)  # Deaktywacja skrótów klawiszowych
        self.closingPlugin.emit()
        event.accept()
